# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='date_time',
        ),
    ]
