# Generated by Django 2.0.7 on 2018-08-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('users', '0002_auto_20180802_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('livereservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.LiveReservation')),
                ('jwt_token', models.TextField()),
            ],
            bases=('reservations.livereservation',),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
