# Generated by Django 2.0.7 on 2018-08-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180805_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreservation',
            name='livereservation_ptr',
        ),
        migrations.DeleteModel(
            name='UserReservation',
        ),
    ]
