# Generated by Django 2.0.7 on 2018-07-31 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='slot',
            name='management__buildin_7d8ace_idx',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='building',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='floor',
        ),
        migrations.AlterField(
            model_name='slot',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Segment'),
        ),
        migrations.AddField(
            model_name='segment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Floor'),
        ),
        migrations.AddField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Building'),
        ),
    ]
