# Generated by Django 2.0.7 on 2018-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180731_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2018-07-31 16:51:54.145880'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='label',
            field=models.CharField(default='#', max_length=32),
            preserve_default=False,
        ),
    ]
