# Generated by Django 2.0.7 on 2018-08-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180731_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
