# Generated by Django 2.0.7 on 2018-08-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name_plural': 'buildings'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name_plural': 'floors'},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name_plural': 'segments'},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name_plural': 'slots'},
        ),
    ]
