# Generated by Django 2.0.7 on 2018-08-06 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20180802_0708'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20180806_0518'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('jwt_token', models.TextField()),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reservations',
            },
        ),
        migrations.RemoveField(
            model_name='livereservation',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='livereservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='LiveReservation',
        ),
    ]
